"use client";
import { useState } from "react";
import { AppChrome } from "@/components/AppChrome";
import { AuthGate } from "@/components/AuthGate";
import { getBankingOptions, type CardOption } from "@/lib/api";

export default function BankingPage() {
  const [purpose, setPurpose] = useState("Travel"); const [options, setOptions] = useState<CardOption[]>([]); const [summary, setSummary] = useState(""); const [note, setNote] = useState(""); const [status, setStatus] = useState("");
  async function compare() { setStatus("Comparing issuer information..."); try { const data = await getBankingOptions(purpose); setOptions(data.options); setSummary(data.summary); setNote(data.affordability_note); setStatus(`Compared ${data.options.length} options`); } catch (e) { setStatus(e instanceof Error ? e.message : "Comparison failed"); } }
  return <AuthGate><AppChrome app><section className="section template-shell"><div className="kicker">Decision research · banking</div><h1 className="serif section-title">Choose a card for the actual reason you need it.</h1><p className="hero-copy compact-copy">Issuer-linked comparisons, fees, rates, eligibility, and a budget-aware caution. Liminal does not treat credit as income.</p><section className="research-filters panel-pad"><label className="field"><span className="label">Primary purpose</span><select className="input" value={purpose} onChange={e => setPurpose(e.target.value)}><option>Travel</option><option>Fuel</option><option>Groceries</option><option>Online purchases</option><option>Emergency expenses</option></select></label><button className="btn primary" onClick={compare}>Compare cards</button></section>{summary ? <div className="research-location">{summary}</div> : null}{note ? <div className="budget-alert">{note}</div> : null}<p className="source">{status}</p><div className="research-grid">{options.map(card => <article className="template-card research-card" key={`${card.issuer}-${card.name}`}><div className="kicker">{card.issuer} · {card.card_type}</div><h2>{card.name}</h2><p><strong>Best for:</strong> {card.best_for}</p><p><strong>Annual fee:</strong> {card.annual_fee} · <strong>Joining:</strong> {card.joining_fee}</p><p><strong>Interest:</strong> {card.interest_rate} · <strong>Forex:</strong> {card.forex_fee}</p><p><strong>Rewards:</strong> {card.rewards}</p><p><strong>Eligibility:</strong> {card.eligibility}</p><p><strong>Caution:</strong> {card.caution}</p><a className="btn" href={card.source_url} target="_blank" rel="noreferrer">Official issuer source</a></article>)}</div>{options.length > 1 ? <section className="panel-pad comparison-graph"><div className="kicker">Comparison view</div><p className="source">Relative fit is based on the returned purpose-specific recommendation. Verify every fee and rate on the linked issuer page.</p>{options.map((card, index) => <div className="graph-row" key={card.name}><span>{card.name}</span><div><i style={{ width: `${Math.max(18, 100 - index * Math.floor(70 / options.length))}%` }} /></div></div>)}</section> : null}</section></AppChrome></AuthGate>;
}
